### ISSUE TITLE
[12/12~12/13] TODO gagori

### ISSUE THREAD

**Issue by gagori** [gagori/project03#1]
- [x] 전처리 최종안 선별 
- [x] skew correction 구현 ( 논문참고 )
- [x] 이제까지 내용 ppt / 깃블로그 업데이트

**Comment by gagori** [comment]
굳
