### ISSUE TITLE
[12/15~12/16] TODO gagori

### ISSUE THREAD

**Issue by gagori** [gagori/project03#3]
- [x] skew.py 수정 << driver1 90도 회전문제
- [x] face detection에 YOLOv3 적용해보기
- [x] location 이용해서 text detection 성능 높이기  **with pattern ????**
- [x] 깃블로그 정리 + ppt 중간발표(12/17) 자료 정리

**Comment by gagori** [comment]
location활용은 좋음. 이후에서 text detection모델을 학습시켜보는건 어떨까?
