### ISSUE TITLE
12/15~12/16 TODO YJ

### ISSUE THREAD

**Issue by jjeong7097** [gagori/project03#4]
12/15 ~ 12/16
- [x] 부트스트랩 템플릿 붙이기
- [x] 개인정보 종류 구별하기

12/17 ~ 12/22
- [x] 개인정보 패턴 별로 마스킹 위치 수정
- [x] 이미지 업로드 시 파일 저장하게 수정
- [x] 이미지 경로 수정 (static 안에 origin / result)
- [x] 웹 디자인 꾸미기 (메뉴바 등)
- [x] 테스트 이미지/ 패턴 이미지 변경
- [x] 최종 PPT 꾸미기
