### ISSUE TITLE
[12/18~12/21] TODO gagori

### ISSUE THREAD

**Issue by gagori** [gagori/project03#9]
- [ ] ocr 진행을 위한 데이터셋 확보
- [x] text detection 모델 설정
- [ ] text recognition 모델 설정
- [x] save Model and apply to our prj3

**Comment by gagori** [comment]
detection by CRAFT 
적용시 ROI 잘잡음
그러나 우리프로젝트에 적용하기에 너무 많은 TEXT를 잡음  >> _모든 TEXT 가릴 때는 용이할듯_
뭐가 이름이고 뭐가 주소고 뭐가 Id number 인지 구분하기 어려움

**따라서  ROI by CRAFT 보다는 ROI by regionselector 가 더 적합해 보임**
